// The built-in songs as the server sees them (from shared/chart-objects.json, generated by
// `npm run charts`): which charts exist, how long each song is and the highest score possible.
// Imported songs never reach the server: they only exist on one player's computer.
import { readFileSync } from 'node:fs';

/** @type {Map<string, { id: string, title: string, difficulty: string, duration: number, charts: Record<string, number> }>} */
export const SONGS = new Map();
try {
  const data = JSON.parse(readFileSync(new URL('../../shared/chart-objects.json', import.meta.url), 'utf8'));
  for (const [id, s] of Object.entries(data)) SONGS.set(id, { id, ...s });
} catch (err) {
  console.error('[catalog] could not read shared/chart-objects.json', err);
}

export const DIFF_LABEL = { Easy: 'EASY', Hard: 'HARD', Expert: 'EXPERT', Extreme: 'EXTREME', Insane: 'INSANE' };
export const RANK = { Easy: 1, Hard: 2, Expert: 3, Extreme: 4, Insane: 5 };

/** a chart that exists: the song's own tier or its "+" chart */
export const chartExists = (songId, diff) => typeof diff === 'string' && Object.hasOwn(SONGS.get(songId)?.charts ?? {}, diff);

/** every object Perfect at x4 combo with the biggest possible style / speed / modifier multiplier */
export const maxScore = (songId, diff) => (SONGS.get(songId)?.charts[diff] ?? 0) * 300 * 4 * 2.8;
